
myrobot:
 # Publish all joint states -----------------------------------
#Configuation for robot odometry EKF
#
  frequency: 50
  odom0: //diffbot/base_controller/odom
  odom0_config: [false, false, false,
  false, false, false,
  true, true, true,
  false, false, true,
  false, false, false]
  odom0_differential: false
  imu0: /diffbot/base_controller/imu
  imu0_config: [false, false, false,
  false, false, true,
  false, false, false,
  false, false, true,
  true, false, false]
  imu0_differential: false
  odom_frame: odom
  base_link_frame: base_footprint
  world_frame: odom
